# Generated by Django 4.1.3 on 2023-01-04 12:57

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_project_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
